### ISSUE TITLE
didn't work

### ISSUE THREAD

**Issue by 4yuub** [0xPacman/GITscript#1]
os: "Linux MyUbuntu 5.13.0-30-generic #33-Ubuntu SMP Fri Feb 4 17:03:31 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux"
![Screenshot from 2022-03-11 02-16-01](https://user-images.githubusercontent.com/73800543/157783186-6059b309-d99b-4e8b-bb63-6e2ad621ef2b.png)

**Comment by 0xPacman** [comment]
The bug is fixed and i hope it works for you now, kindly keep me updated if you faced any other issue.

**Comment by 0xPacman** [comment]
another bug that has been reported locally about `/list`, been solved.
